# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool: default
steps:
- script: | 
    echo ${{ parameters.myname }}!
    echo ${{ parameters.vmsize }}!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
    
- task: TerraformCLI@0
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Visual Studio Enterprise Subscription – MPN(5ddead9e-013d-441f-a427-d808cac56f31)'
    allowTelemetryCollection: true
    publishPlanResults: 'terraform plannywanny'
    commandOptions: -out=$(System.DefaultWorkingDirectory)/tfplanny.txt -var="vmsize=${{ parameters.vmsize }}"
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/tfplanny.txt'
    artifact: 'tfplanny.txt'
    publishLocation: 'pipeline'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '2e010af1-46d5-4ba9-88af-33fe7afa61aa'
    definition: '1'
    buildVersionToDownload: 'latest'
    artifactName: 'tfplanny.txt'
    # targetPath: '$(System.DefaultWorkingDirectory)/tfplanny.txt'
    
    


parameters:
- name: vmsize
  displayName: vm sizes
  type: string
  default: 
  values:
  - DS1_v2
  - D2s_v3
  - D2as_v4
- name: myname
  displayName: my name
  type: string